### ISSUE TITLE
Question about multi-metrics optimization

### ISSUE THREAD

**Issue by shengminp** [JuYeon28/RS-OtterTune#3]
Hello!

I am also a developer of DBMS, especially in RocksDB.
As far as I know, there is more than one metric that can be optimized (ex. latency, throughput), how can I apply RS-OtterTune to this multi-optimization subject, specifically?

**Comment by kimkyeonghun** [comment]
In RS-OtterTune, we make three DNN models like single, twice and double.
we will update README.md in the future for your question.

**Comment by rlagnlrns** [comment]
Okay, I got it.
Thanks a lot.

**Comment by shengminp** [comment]
Okay, I got it.
Thanks a lot.
